package me.timickb.jigsaw.messenger;

public enum MessageType {
    DISCONNECT, GAME_OVER, LOGIN, AUTHORIZED, ERROR, LEAVE, FIGURE_PLACED, SOMEONE_LEFT, SCORE_UPDATED, NEW_FIGURE,
    GAME_STARTED, STATS_REQUEST, STATS_RESPONSE, GAME_TABLE, CLIENT_TIMER_READY
}
